-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

ALTER TABLE IF EXISTS public.notes
    ADD COLUMN body text COLLATE pg_catalog."default" NOT NULL;

ALTER TABLE IF EXISTS public.notes
    ADD COLUMN preview_text text COLLATE pg_catalog."default" NOT NULL;

ALTER TABLE IF EXISTS public.notes
    ADD COLUMN title text COLLATE pg_catalog."default" NOT NULL;

ALTER TABLE IF EXISTS public.notes
    ADD COLUMN updated_at timestamp without time zone DEFAULT now();
